apiVersion: v1
kind: Service
metadata:
 name: pcl-svc
spec:
 type: NodePort
 ports:
 - port: 8080
   targetPort: 8080
   nodePort: 31111
 selector:
  app: pcl

---
# Headless service for stable DNS entries
apiVersion: v1
kind: Service
metadata:
  name: pcl
  labels:
    app: pcl
spec:
  ports:
  - name: pcl
    port: 8080
  clusterIP: None
  selector:
    app: pcl



