apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0
spec:
  storageClassName: managed-nfs-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.160.0.2
    path: "/pdb"
  mountOptions:
    - nfsvers=4.2
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
spec:
  storageClassName: managed-nfs-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.160.0.2
    path: "/sdb"
  mountOptions:
    - nfsvers=4.2
